# Generated by Django 4.0.4 on 2022-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserServicesChtghFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_column='USER_ID', null=True)),
                ('arn', models.TextField(blank=True, db_column='ARN', null=True)),
                ('application_id', models.FloatField(blank=True, db_column='APPLICATION_ID', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CREATED_ON', null=True)),
                ('modified_on', models.DateTimeField(blank=True, db_column='MODIFIED_ON', null=True)),
                ('product_id', models.BigIntegerField(blank=True, db_column='PRODUCT_ID', null=True)),
                ('user_geography_id', models.FloatField(blank=True, db_column='USER_GEOGRAPHY_ID', null=True)),
                ('form_id', models.BigIntegerField(blank=True, db_column='FORM_ID', null=True)),
                ('state', models.TextField(blank=True, db_column='STATE', null=True)),
                ('district', models.TextField(blank=True, db_column='DISTRICT', null=True)),
                ('tehsil_id', models.FloatField(blank=True, db_column='TEHSIL_ID', null=True)),
                ('scheme_name', models.TextField(blank=True, db_column='SCHEME_NAME', null=True)),
                ('corporation', models.TextField(blank=True, db_column='CORPORATION', null=True)),
                ('department', models.TextField(blank=True, db_column='DEPARTMENT', null=True)),
                ('application_status', models.TextField(blank=True, db_column='APPLICATION_STATUS', null=True)),
                ('role_sla', models.FloatField(blank=True, db_column='ROLE_SLA', null=True)),
                ('limit_status', models.TextField(blank=True, db_column='LIMIT_STATUS', null=True)),
                ('dsc_role_id', models.FloatField(blank=True, db_column='DSC_ROLE_ID', null=True)),
                ('dsc_role', models.TextField(blank=True, db_column='DSC_ROLE', null=True)),
                ('dsc_name', models.TextField(blank=True, db_column='DSC_NAME', null=True)),
                ('dsc_user_id', models.FloatField(blank=True, db_column='DSC_USER_ID', null=True)),
                ('verifier_code', models.TextField(blank=True, db_column='VERIFIER_CODE', null=True)),
                ('verifier_lgd', models.TextField(blank=True, db_column='VERIFIER_LGD', null=True)),
                ('verifier_name', models.TextField(blank=True, db_column='VERIFIER_NAME', null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('ranking', models.FloatField(blank=True, null=True)),
                ('accounts', models.TextField(blank=True, db_column='ACCOUNTS', null=True)),
                ('division', models.TextField(blank=True, db_column='DIVISION', null=True)),
                ('tehsil_name', models.TextField(blank=True, db_column='TEHSIL_NAME', null=True)),
                ('office_name', models.TextField(blank=True, db_column='OFFICE_NAME', null=True)),
                ('role_type', models.TextField(blank=True, db_column='ROLE_TYPE', null=True)),
                ('applicant_name', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_column='DUE_DATE', null=True)),
                ('within_limit', models.TextField(blank=True, db_column='WITHIN_LIMIT', null=True)),
                ('beyond_limit', models.TextField(blank=True, db_column='BEYOND_LIMIT', null=True)),
                ('due_date_in_2_days', models.TextField(blank=True, null=True)),
                ('admin_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('application_district', models.CharField(blank=True, db_column='APPLICATION_DISTRICT', max_length=255, null=True)),
                ('lgd_code', models.BigIntegerField(blank=True, db_column='LGD_CODE', null=True)),
                ('census', models.CharField(blank=True, db_column='CENSUS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'UserServicesChtghFinal',
                'managed': False,
            },
        ),
    ]
