# Generated by Django 4.0.4 on 2022-06-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userserviceschtghfinal',
            table='user_services_chtgh_final',
        ),
    ]
